from enum import StrEnum

class AccessFlag(StrEnum):
    ACC_PUBLIC = "ACC_PUBLIC"
    ACC_FINAL = "ACC_FINAL"
    ACC_SUPER = "ACC_SUPER"
    ACC_INTERFACE = "ACC_INTERFACE"
    ACC_ABSTRACT = "ACC_ABSTRACT"
    ACC_SYNTHETIC = "ACC_SYNTHETIC"
    ACC_ANNOTATION = "ACC_ANNOTATION"
    ACC_ENUM = "ACC_ENUM"
    ACC_MODULE = "ACC_MODULE"
    ACC_PRIVATE = "ACC_PRIVATE"
    ACC_PROTECTED = "ACC_PROTECTED"
    ACC_STATIC = "ACC_STATIC"
    ACC_VOLATILE = "ACC_VOLATILE"
    ACC_TRANSIENT = "ACC_TRANSIENT"